#!/bin/sh

#remove shiftfs with dkms

#functions:

dkms_remove () {
dkms remove -m shiftfs -v $MODVERNOW --all
echo ' '
#delete /usr/src folder
echo ' You can delete the shiftfs folders in "/usr/src", for example 
"/usr/src/shiftfs-1.1" '
#rm -r /usr/src/shiftfs-$MODVERNOW
}

version_check3 () {
ls /usr/src/
echo ' '
read -p "Type in the most recent version number of shiftfs (e.g. '1.0'), you see above:" num2
MODVERNOW=${num2}
dkms_remove
}

#is not used now
version_check2 () {
if [ $VER1 != 0 ]; then
echo ' '
echo 'Installed shiftfs version:'
echo $VER1
echo ' '
read -p "Type in the version number of shiftfs (e.g. '1.0'):" num1
MODVERNOW=${num1}
dkms_remove
else
echo ' '
echo 'The folder of shiftfs in "/usr/src" was not found.'
echo 'You can try to search for it manually (e.g. in "/usr/src/"). '
echo 'If you found it, note down the version number (e.g. "1.0").'
echo ' '
echo "If you can't find it, check if shiftfs is installed (modinfo shiftfs). "
echo 'If it is installed, create an issue report (See: README.md) and skip the next question. '
echo ' '
read -p "Do you want to type in the version number manually? (yes or no):" anws1
     if [ $anws1 = yes ]; then
     version_check3
     else 
     exit
fi
fi
}

#is not used now
version_check1 () {
VER1=$(ls /usr/src | grep shiftfs)
version_check2
}

#####
#Start of script

#read username
USERNAME=$(whoami)

#check if run as root
if [ $USERNAME != root ]; then
echo 'You need to run this script as root or with sudo.'  
else 
version_check3   
exit    
fi
